[package]
name = "docs"
version = "0.1.0"
edition = "2021"
description = "Docs"

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_yaml = "^0"
tera = "^1"
lazy_static = "^1"
